### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rgbkrk** [gboeing/urban-data-science#1]
Hey @gboeing can you put a license on these notebooks? I'd love to include them in some example/test notebooks in [nteract](https://github.com/nteract/nteract).

In particular, I want to show how to go straight from geojson to rendered:

<img width="1433" alt="screen shot 2016-09-06 at 11 04 22 am" src="https://cloud.githubusercontent.com/assets/836375/18285432/32b2ca58-7423-11e6-8c77-c07f68fab4d8.png">

nteract PR for direct geoJSON support: https://github.com/nteract/nteract/pull/688

**Comment by gboeing** [comment]
Sure @rgbkrk I'll add a license today.

**Comment by rgbkrk** [comment]
Thanks! Love the materials here, looking forward to going through them now that I've stumbled on to them. 😄

**Comment by gboeing** [comment]
Add license file. Cheers.
