### ISSUE TITLE
Parameter missing

### ISSUE THREAD

**Issue by harisbal** [gboeing/urban-data-science#2]
line geometry_cut = ox.quadrat_cut_geometry(geometry) 
throws an error 
"quadrat_cut_geometry() missing 1 required positional argument: 'quadrat_width'"

It would probably be a good idea to have an optional parameter there (e.g. max width/10, you know better)

**Comment by gboeing** [comment]
Which notebook and cell/line specifically are you referring to?

**Comment by harisbal** [comment]
I'm sorry I though I had opened the issue just for a specific notebook.
The notebook is: https://github.com/gboeing/urban-data-science/blob/master/19-Spatial-Analysis-and-Cartography/rtree-spatial-indexing.ipynb
line: In [18]:

Thank you for all this interesting material you have uploaded.
