### ISSUE TITLE
AssertionError: Adding more networks than have been reserved

### ISSUE THREAD

**Issue by ariannasm** [gboeing/urban-data-science#6]
hi Geoff, 

I am trying to query the OSM API for the street network specifying this bounding box
bbox = [6.196,-75.575, 6.212, -75.553] and I encounter the following error:

AssertionErrorTraceback (most recent call last)
<ipython-input-45-d42ce103ba8c> in <module>()
----> 1 network = osm.network_from_bbox(bbox[0], bbox[1], bbox[2], bbox[3])

/Users/arianna/anaconda/envs/Access/lib/python2.7/site-packages/pandana-0.2.0-py2.7-macosx-10.5-x86_64.egg/pandana/loaders/osm.py in network_from_bbox(lat_min, lng_min, lat_max, lng_max, network_type, two_way)
    320     return Network(
    321         nodes['lon'], nodes['lat'],
--> 322         pairs['from_id'], pairs['to_id'], pairs[['distance']])
    323 
    324 

/Users/arianna/anaconda/envs/Access/lib/python2.7/site-packages/pandana-0.2.0-py2.7-macosx-10.5-x86_64.egg/pandana/network.py in __init__(self, node_x, node_y, edge_from, edge_to, edge_weights, twoway)
     99             reserve_num_graphs(1)
    100 
--> 101         assert NUM_NETWORKS < MAX_NUM_NETWORKS, "Adding more networks than " \
    102                                                 "have been reserved"
    103         self.graph_no = NUM_NETWORKS

AssertionError: Adding more networks than have been reserved

Any idea what might be going wrong?

thanks,

**Comment by gboeing** [comment]
If you specifically want to do this with pandana I'd suggest asking the question at its repo. If you alternatively are just trying to query OSM for street network analysis, you can consider [OSMnx](https://github.com/gboeing/osmnx) which can be an easier lift.
