### ISSUE TITLE
osm network from bounding box error: 'Server at www.overpass-api.de returned status code 400 and no JSON data' 

### ISSUE THREAD

**Issue by MartijnVerhoeven** [gboeing/urban-data-science#8]
Hi Geoff, 

Thank you so much for you contributions, they have been very valuable! I have the following issue regarding walkabality/accessability analysis. I've managed to download the POI's of Amsterdam that I'm interested in but when trying to get the network from osm, it produces the following error:  ' Server at www.overpass-api.de returned status code 400 and no JSON data' 

I've tried on multiple locations with different bounding box coordinates however, I can't manage to get it to work. Is there something that I've overlooked?

Kind regards,

Martijn Verhoeven

**Comment by gboeing** [comment]
Can you provide a minimal working example code snippet?

**Comment by MartijnVerhoeven** [comment]
Hi Geoff,

Thank you for your reply. Below is what I've got so far:

`import pandana, time, os, pandas as pd, numpy as np, osmnx as ox
from pandana.loaders import osm
%matplotlib inline

amenity = ['school'] #type voorziening Amsterdam
distance = 1500
num_pois = 10
num_categories = len(amenity) + 1

bbox = [52.284542,4.711761,52.444292,5.044785] #coordinaten uitsnede kaart Amsterdam

bbox_string = '_'.join([str(x) for x in bbox])
net_filename = 'data/network_{}.h5'.format(bbox_string)
poi_filename = 'data/pois_{}_{}.csv'.format('_'.join(amenity), bbox_string)

# keyword arguments to pass for the matplotlib figure
bbox_aspect_ratio = (bbox[2] - bbox[0]) / (bbox[3] - bbox[1])
fig_kwargs = {'facecolor':'w', 
              'figsize':(10, 10 * bbox_aspect_ratio)}

# keyword arguments to pass for scatter plots
plot_kwargs = {'s':5, 
               'alpha':0.9, 
               'cmap':'viridis_r', 
               'edgecolor':'none'}

# network aggregation plots are the same as regular scatter plots, but without a reversed colormap
agg_plot_kwargs = plot_kwargs.copy()
agg_plot_kwargs['cmap'] = 'viridis'

# keyword arguments to pass for hex bin plots
hex_plot_kwargs = {'gridsize':60,
                   'alpha':0.9, 
                   'cmap':'viridis_r', 
                   'edgecolor':'none'}

# keyword arguments to pass to make the colorbar
cbar_kwargs = {}

# keyword arguments to pass to basemap
bmap_kwargs = {}

# color to make the background of the axis
bgcolor = 'k'

start_time = time.time()
osm_tags = '"amenity"~"{}"'.format('|'.join(amenity))
pois = osm.node_query(bbox[0], bbox[1], bbox[2], bbox[3], tags=osm_tags)

pois = pois[pois['amenity'].isin(amenity)]
pois.to_csv(poi_filename, index=False, encoding='utf-8')
method = 'downloaded from OSM'

print('{:,} POIs {} in {:,.2f} seconds'.format(len(pois), method, time.time()-start_time))
pois[['amenity', 'name', 'lat', 'lon']].head()`

pois['amenity'].value_counts()

school    115
Name: amenity, dtype: int64

start_time = time.time()
network = osm.network_from_bbox(bbox[0], bbox[1], bbox[2], bbox[3])
method = 'downloaded from OSM'

**And this is the error message that I've received**

Requesting network data within bounding box from Overpass API in 1 request(s)
Posting to http://www.overpass-api.de/api/interpreter with timeout=180, "{'data': '[out:json][timeout:180];(way["highway"]["highway"!~"motor|proposed|construction|abandoned|platform|raceway"]["foot"!~"no"]["pedestrians"!~"no"](inf,inf,inf,inf);>;);out;'}"
Downloaded 0.6KB from www.overpass-api.de in 12.35 seconds
Server at www.overpass-api.de returned status code 400 and no JSON data

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
~\Miniconda3\lib\site-packages\osmnet\load.py in overpass_request(data, pause_duration, timeout, error_pause_duration)
    240     try:
--> 241         response_json = response.json()
    242         if 'remark' in response_json:

~\Miniconda3\lib\site-packages\requests\models.py in json(self, **kwargs)
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 

~\Miniconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:

~\Miniconda3\lib\json\decoder.py in decode(self, s, _w)
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()

~\Miniconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-10-15b4a4b3c832> in <module>
      1 start_time = time.time()
----> 2 network = osm.network_from_bbox(bbox[0], bbox[1], bbox[2], bbox[3])
      3 method = 'downloaded from OSM'

~\Miniconda3\lib\site-packages\osmnet\load.py in network_from_bbox(lat_min, lng_min, lat_max, lng_max, bbox, network_type, two_way, timeout, memory, max_query_area_size, custom_osm_filter)
    852         network_type=network_type, timeout=timeout,
    853         memory=memory, max_query_area_size=max_query_area_size,
--> 854         custom_osm_filter=custom_osm_filter)
    855     log('Returning OSM data with {:,} nodes and {:,} ways...'
    856         .format(len(nodes), len(ways)))

~\Miniconda3\lib\site-packages\osmnet\load.py in ways_in_bbox(lat_min, lng_min, lat_max, lng_max, network_type, timeout, memory, max_query_area_size, custom_osm_filter)
    656                          timeout=timeout, memory=memory,
    657                          max_query_area_size=max_query_area_size,
--> 658                          custom_osm_filter=custom_osm_filter))
    659 
    660 

~\Miniconda3\lib\site-packages\osmnet\load.py in osm_net_download(lat_min, lng_min, lat_max, lng_max, network_type, timeout, memory, max_query_area_size, custom_osm_filter)
    162                                           timeout=timeout, maxsize=maxsize)
    163         response_json = overpass_request(data={'data': query_str},
--> 164                                          timeout=timeout)
    165 
    166         response_jsons_list.append(response_json)

~\Miniconda3\lib\site-packages\osmnet\load.py in overpass_request(data, pause_duration, timeout, error_pause_duration)
    266                 .format(domain, response.status_code), level=lg.ERROR)
    267             raise Exception('Server returned no JSON data.\n{} {}\n{}'
--> 268                             .format(response, response.reason, response.text))
    269 
    270     return response_json

Exception: Server returned no JSON data.
<Response [400]> Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" lang="en"/>
  <title>OSM3S Response</title>
</head>
<body>

<p>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</p>
<p><strong style="color:#FF0000">Error</strong>: line 1: parse error: Unknown query clause </p>

</body>
</html>

**Comment by MartijnVerhoeven** [comment]
Hi Geoff, 

Without changing anything, the code now retrieves the network from the overpass Api. However, when I want to save the network to a hdf5 format or run the subsequent steps, I recieve the error: 'tuple' object has no attribute 'save_hdf5'. I read online that this might be solved by installing a virtual environment but nothing changed once I did this. Do you have any advice on solving the tuple error?

Kind regards,

Martijn Verhoeven
