### ISSUE TITLE
ox.quadrat_cut_geometry not available anymore?

### ISSUE THREAD

**Issue by eccc-Antoine** [gboeing/urban-data-science#9]
Hi, I freshly installed osmnx 0.15.1 on Linux from conda-forge channel. 

I try to run an old code using the technique described in your article (https://geoffboeing.com/2016/10/r-tree-spatial-index-python/)

at this line :

geometry_cut = ox.quadrat_cut_geometry(geometry, quadrat_width=0.1)

I get an error message saying that osmnx doesn't have  "quadrat_cut_geometry" attribute

Downgrading to osmnx 0.10 with "conda install -c conda-forge osmnx=0.10" command. I run the same code and everything runs fine!

Therefore I'm just asking if "ox.quadrat_cut_geometry" is not available in newer version of osmnx? If so, what it has been replaced with? And maybe an update of this really usefull article would be needed.

Thanks for your great work!

**Comment by gboeing** [comment]
Thanks for the heads-up. Yes it is still available as an internal function. See https://github.com/gboeing/osmnx/issues/526 for details of how to access it now. See also its [documentation](https://osmnx.readthedocs.io/en/stable/osmnx-complete.html#osmnx-utils-geo-module) in the OSMnx internals reference. I'll update that old blog post so it works with recent OSMnx releases.

**Comment by eccc-Antoine** [comment]
Thanks!
